Feelings/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from users import urls as users_urls
from thoughts import urls as thought_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include(users_urls,namespace='users')),
    url(r'^thoughts/',include(thought_urls,namespace='thoughts')),
    url(r'^$',TemplateView.as_view(template_name="index.html"),name="home"),
]

thoughts/urls.py
__author__ = 'PRITHVIRAJ'

from django.conf.urls import url
from . import views

urlpatterns =[
    url(r'^create/$',views.CreateThought.as_view(),name="create"),

]

users/urls.py
__author__ = 'PRITHVIRAJ'

from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^logout/$',views.LogOutView.as_view(),name="logout"),
    url(r'^',include('django.contrib.auth.urls')),
    url(r'^signup/$',views.signUpView.as_view(),name="signup"),
    url(r'^dashboard/$',views.dashboard,name="dashboard"),
]

thoughts/models.py
from django.db import models
from django .contrib.auth.models import User
from django.utils import timezone
# Create your models here.

conditions = (
        (1,'Joy'),
        (5,'Passionate'),
        (10,'Happy'),
        (15,'Positive'),
        (20,'Optimistic'),
        (25,'Bored'),
        (30,'Pessimistic'),
        (35,'Frustrated'),
        (40,'overwhelmed'),
        (45,'angry'),
)

class Thought(models.Model):
    user = models.ForeignKey(User, related_name='thoughts')
    recorded = models.DateTimeField(default=timezone.now , editable = False)
    condition = models.IntegerField(choices = conditions)
    notes = models.TextField(blank = True,default='')

    def  __str__(self):
        return '{}:{}'.format(self.recorded.strftime('%Y-%m-%d %H:%M:%S '),self.get_condition_display())

users/models.py
from django.db import models

# Create your models here.

thoughts/forms.py
__author__ = 'PRITHVIRAJ'

from django import forms
from . import models

class ThoughtForm(forms.ModelForm):
    class Meta:
        fields ={'condition','notes'}
        model = models.Thought

users/forms.py
__author__ = 'PRITHVIRAJ'

from django import forms

class LogOutForm(forms.Form):
    pass

thoughts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from .forms import ThoughtForm
from django.core.urlresolvers import reverse_lazy

# Create your views here.

class CreateThought(LoginRequiredMixin, CreateView):
    form_class = ThoughtForm
    success_url = reverse_lazy('users:dashboard')

    def get_object(self, queryset=None):
        select_related =['thoughts']
        return self.request.user

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

users/views.py
from django.shortcuts import render
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import FormView,CreateView
from django.http import HttpResponseRedirect
from django.core.urlresolvers import  reverse,reverse_lazy
from . import forms
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

def dashboard(request):
    return render(request,'users/dashboard.html')


class LogOutView(LoginRequiredMixin,FormView):
    template_name = 'users/logout.html'
    form_class = forms.LogOutForm

    def form_valid(self,form):
        logout(self.request)
        return HttpResponseRedirect(reverse('home'))

class  signUpView(CreateView):
    form_class = UserCreationForm
    template_name = "users/signUpVIew.html"
    success_url = reverse_lazy('users:dashboard')

templates/index.html
{% extends "layout.html" %}

{% block content %}
     <div class="jumbotron">
      <div class="container">
        <h1>Feelings</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} Feelings {% endblock %}</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel ="stylesheet" href="{% static 'css/feelings.css' %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <![endif]-->
  </head>
  <body>
     <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Feelings</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
              <li><a href="{% url 'users:login' %}">LOGIN</a></li>
              <li><a href="{% url 'users:signup' %}">SIGN UP</a></li>
            {% else %}
                <li><a href="{% url 'users:dashboard' %}"> DASHBOARD </a></li>
                <li> <a href="{% url 'users:logout' %}"> LOGOUT </a></li>
            {% endif %}
            </ul>
        </div>
        <!--/.navbar-collapse -->
      </div>
    </nav>

    <div id="content">
    {% block content %}{% endblock %}
    </div>

     <div class="container">
         <hr>

      <footer>
        <p>&copy; 2017 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->
     </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

  </body>
</html>

thoughts/templates/thoughts/thoughts_form.html
{% load bootstrap3 %}

<form method="POST" action="{% url 'thoughts:create' %}">
    <h2> How're you Feeling </h2>
    <div class ="row">
        <div class="col-md-4">{% bootstrap_field form.condition %}</div>
        <div class="col-md-8">{% bootstrap_field form.notes %}</div>
    </div>
    {% csrf_token %}
    <input type="submit" value="Record" class="btn btn ">
</form>

users/templates/users/SignUpView.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{% block title %} SignUp | {{ block.super }} {% endblock %}

{% block content %}
    <div class="container pt">
        <div class="row">
            <div class="col-md-6">
                <form action="" method="POST">
                    {% bootstrap_form form %}
                    {% csrf_token %}
                    <input type="submit" value="SignUp" class="btn btn-primary">
                </form>
            </div>
            <div class="col-md-6">
                <h3> Login to record how you're feeling </h3>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/dashboard.html
{% extends "layout.html" %}

{% load thought_tags %}

{% block title %}Dashboard | {{ block.super }}{% endblock %}

{% block content %}
<div class="container">
    {% thought_form %}
    <hr>
    <h3>Recent Thoughts</h3>
    <div class="row">
        <div class="col-md-6">
            <ul>
                {% for thoughts in user.thoughts.all %}
                <li>{{ thoughts.get_condition_display }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends "layout.html" %}

{%  block title %} Logout | {{ block.super }} {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div clas="col-md-6">
            <h1>Logout</h1>
            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Logout" class="btn btn-default">
            </form>
        </div>
        <div class="col-md-6">
            <h3>Sorry to see you Go</h3>
            <p>Come Back Soon</p>
        </div>
    </div>
</div>
{% endblock %}